### ISSUE TITLE
NLP for dates 

### ISSUE THREAD

**Issue by uncenter** [MatthiasGrandl/loungy#12] opened 2024-02-09 17:39 UTC
Numbat supports mathematical calculations just fine but it doesn't have date calculations like Raycast. I looked around for some date NLP libraries in Rust but couldn't find many still maintained, maybe you or other people know of some though.

![Screenshot 2024-02-09 at 12 37 19 (Arc)](https://github.com/MatthiasGrandl/loungy/assets/47499684/f289f8d2-d6b4-46dc-85bb-90c7bc726d87)

![Screenshot 2024-02-09 at 12 39 21 (Arc)](https://github.com/MatthiasGrandl/loungy/assets/47499684/42fa951d-e6f6-4066-8805-c8c1aa140ea3)

**Comment by MatthiasGrandl** [comment] 2024-02-09 17:41
See: https://github.com/sharkdp/numbat/pull/327 
https://github.com/sharkdp/numbat/pull/287 (merged just 2 hours ago)

**Comment by uncenter** [comment] 2024-02-09 17:42
Oh wow! The timing ahah. Can't wait to see that for loungy :)

**Comment by MatthiasGrandl** [comment] 2024-02-09 17:44
Yeah I hope Numbat will be enough to support this. To be honest the calculator in raycast is super dope and just feels very natural. Numbat is definitely much more strict with their inputs.

**Comment by MatthiasGrandl** [comment] 2024-02-09 17:47
There is also this https://erhanbaris.github.io/smartcalc-app/ which might be worth looking into. Although I am not sure if it is abandoned. It seems to be better for this usecase than numbat though and pretty close to raycast.

**Comment by MatthiasGrandl** [comment] 2024-02-09 17:54
Oh and there is also https://github.com/printfn/fend ...

**Comment by uncenter** [comment] 2024-02-09 19:43
> There is also this [erhanbaris.github.io/smartcalc-app](https://erhanbaris.github.io/smartcalc-app/) which might be worth looking into. Although I am not sure if it is abandoned. It seems to be better for this usecase than numbat though and pretty close to raycast.

Ooh this does look good!

**Comment by sharkdp** [comment] 2024-02-10 13:07
> To be honest the calculator in raycast is super dope and just feels very natural. Numbat is definitely much more strict with their inputs.

Having a strict syntax for Numbat is a design choice. We want users to be able to trust the result of their computations. If you have loose/ambiguous parsing rules, it's sometimes hard to tell if the calculator understands your input in the same way that you do.

> Yeah. Better than nothing I suppose!

As you found out, date-time support has just landed. It's not even released yet (as we might change e.g. function names), but you can play with it on https://numbat.dev/ and/or read the documentation here: https://numbat.dev/doc/date-and-time.html

Please give us feedback and tell us if you think there is something we can improve (ideally, create a new ticket in our repository). There is already a collection of date-time-related enhancements in this ticket: https://github.com/sharkdp/numbat/issues/323.

> There is also this https://erhanbaris.github.io/smartcalc-app/ which might be worth looking into. Although I am not sure if it is abandoned. It seems to be better for this usecase than numbat though and pretty close to raycast.

Interesting reference, I hadn't seen that before. What are some things that smartcalc-app can do that Numbat can't?

Please note that https://github.com/erhanbaris/smartcalc is GPL-2.0 licensed, so integration into your MIT licensed tool is not possible without relicensing.

**Comment by MatthiasGrandl** [comment] 2024-02-10 14:37
@sharkdp thanks for the input! You are definitely right about the license.

> What are some things that smartcalc-app can do that Numbat can't?

i think it’s only the less strict matching that feels better for this usecase. I 100% agree that numbat is the better library overall.

**Comment by uncenter** [comment] 2024-02-10 18:47
> Having a strict syntax for Numbat is a design choice.

I totally understand, I wasn't trying to make a criticism of the library at all, but compared to Raycast a more general syntax might be more favorable.

> As you found out, date-time support has just landed. It's not even released yet (as we might change e.g. function names), but you can play with it on [numbat.dev](https://numbat.dev/) and/or read the documentation here: [numbat.dev/doc/date-and-time.html](https://numbat.dev/doc/date-and-time.html)

I'll try it out and let you know how it is :)

**Comment by sharkdp** [comment] 2024-02-10 20:18
Sorry if I came off as bitter — I'm not! I am actually really excited that you, @MatthiasGrandl, decided to embed Numbat into your tool. I hope that it will be a fruitful collaboration and I'm looking forward to any kind of feedback we can get.

**Comment by sharkdp** [comment] 2024-02-12 09:45
[Numbat v1.10](https://github.com/sharkdp/numbat/releases/tag/v1.10.0) has been released now with initial support for dates & times. We made a couple of changes to the syntax since my last post. See https://numbat.dev/doc/date-and-time.html and https://numbat.dev/doc/conversion-functions.html for an overview of the new features.

**Comment by MatthiasGrandl** [comment] 2024-02-12 10:04
@sharkdp do I need to load some extra module? I just updated, but it doesn't seem to recognize `now()`.

**Comment by sharkdp** [comment] 2024-02-12 10:07
Do you happen to have an old version of the prelude/standard library installed on your system? (e.g. in `~/.config/numbat/modules` or `/usr/share/numbat/modules`)

**Comment by MatthiasGrandl** [comment] 2024-02-12 10:15
I did still have 1.9.0 of the numbat CLI installed. Just removed it and confirmed no `numbat/modules` folder is present, but still can't get it to work 🤔

**Comment by MatthiasGrandl** [comment] 2024-02-12 11:30
I am just using the crate... https://github.com/MatthiasGrandl/loungy/blob/main/src/commands/root/numbat.rs

**Comment by MatthiasGrandl** [comment] 2024-02-12 11:43
> Does use datetime::functions work?

it says datetime is private

**Comment by sharkdp** [comment] 2024-02-12 13:08
> > Does use datetime::functions work?
> 
> it says datetime is private

I meant.. as a Numbat command: `use datetime::functions`.

> it doesn't seem to recognize `now()`.

What is the error message? Do other new features like `42 -> hex` work?

**Comment by MatthiasGrandl** [comment] 2024-02-12 13:14
> What is the error message?

`now()`
```
ResolverError(
    ParseErrors(
        [
            ParseError {
                kind: ExpectedPrimary,
                span: Span {
                    start: SourceCodePositition {
                        byte: 7,
                        line: 1,
                        position: 8,
                    },
                    end: SourceCodePositition {
                        byte: 7,
                        line: 1,
                        position: 8,
                    },
                    code_source_id: 86,
                },
            },
        ],
    ),
)
```

`42 -> hex`

```
TypeCheckError(
    UnknownIdentifier(
        Span {
            start: SourceCodePositition {
                byte: 6,
                line: 1,
                position: 7,
            },
            end: SourceCodePositition {
                byte: 8,
                line: 1,
                position: 9,
            },
            code_source_id: 108,
        },
        "he",
        None,
    ),
)
```

**Comment by sharkdp** [comment] 2024-02-12 13:18
It looks like you're not sending the last character of input to Numbat?

**Comment by MatthiasGrandl** [comment] 2024-02-12 13:26
<img width="912" alt="image" src="https://github.com/MatthiasGrandl/loungy/assets/50196894/1fdd9652-c8ea-40f9-939c-3d73c3a19a12">

jup works nicely!!

**Comment by MatthiasGrandl** [comment] 2024-02-12 13:37
made it a bit prettier and pushed

**Comment by uncenter** [comment] 2024-02-12 14:06
I don't think it makes sense for Numbat to make these changes but it might make sense for Loungy to do some processing on this queries before sending them to Numbat. For example, given `two weeks from now` becomes `now() + two weeks` by replacing `now` with `now()`, `from` with `+`, and switching the order.

**Comment by MatthiasGrandl** [comment] 2024-02-12 14:22
yeah I think that could be easily achieved by matching the phrase `from now`

**Comment by MatthiasGrandl** [comment] 2024-02-12 14:43
<img width="912" alt="image" src="https://github.com/MatthiasGrandl/loungy/assets/50196894/8c671362-e6e5-428f-ac9e-0c38ac8c300c">

**Comment by uncenter** [comment] 2024-02-12 14:44
So cool!

**Comment by MatthiasGrandl** [comment] 2024-02-12 14:50
yeah I am sure more such patterns will come up in the future, but for now that should be good enough :)

**Closed by MatthiasGrandl** 2024-02-12 14:50 UTC
